# ~/.config/starship.toml

"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """
$status\
$directory\
$git_state\
$package\
$fill\
$git_branch\
$git_commit\
$git_time\
$git_metrics\
$git_status\
$cmd_duration\
$line_break\
$character\
"""

[package]
disabled = false
display_private = true
format = '[$symbol$version](magenta) '
symbol = "󰏗 "

[fill]
style = 'green'
symbol = " "
disabled = false

[status]
style = 'fg:blue'
symbol = ' '
success_symbol = ''
format = '$symbol$status$signal_name($style)'
map_symbol = true
disabled = false

[directory]
format = '[\[$path\]]($style)[$read_only]($read_only_style) '
style = "bright-blue"
truncation_length = 0
fish_style_pwd_dir_length = 1
home_symbol = "~"

[character]
success_symbol = "[[](fg)](fg)"
error_symbol = "[](red)"
vimcmd_symbol = "[](green)"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "white"
symbol = '󰘬 '

[git_commit]
commit_hash_length = 7
format = '[\($hash$tag\)]($style) '
style = "yellow"
only_detached = false
tag_disabled = false
tag_symbol = " "

[custom.git_time]
command = "git log -1 --format='%cr'"
when = "git rev-parse --git-dir 2> /dev/null"
format = "[$output]($style) "
style = "yellow"

[git_status]
ahead = '[󱓊 ${count}](blue) '
behind = '󱓋 ${count}'
conflicted = ''
deleted = ' ${count} '
diverged = '󰃻 ${ahead_count}⇣${behind_count} '
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
modified = '[ ${count}](yellow) '
renamed = ''
staged = '[ $count](green) '
stashed = " ${count} "
style = "red"
untracked = "[ ${count}](blue) "
up_to_date = ''

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "fg"
cherry_pick = '[ PICKING](red)'

[git_metrics]
disabled = false
format = '[+$added](green)|[-$deleted](red) '
only_nonzero_diffs = true

[cmd_duration]
format = "[  $duration]($style) "
disabled = false
style = "yellow"
show_notifications = false
min_time = 10_000
min_time_to_notify = 1000
